index:
  path: /
  controller: App\Controller\TestController::index
register:
  path: /register
  controller: App\Controller\AuthController::register
login:
  path: /login
  controller: App\Controller\AuthController::login
